services:
  redis-server:
    image: redis/redis-stack-server:latest
    hostname: redis-server
    restart: always
    volumes:
      - ./redis.conf:/redis-stack.conf
      - ../redis/:/data
    environment:
      ALLOW_EMPTY_PASSWORD: yes

  bot:
    image: docker.io/trickman/klub_ok_tg_bot:latest
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 10
